spring.application.name=CineGraph
debug=true
spring.data.arangodb.hosts=127.0.0.1:8529
spring.data.arangodb.database=cinegraph
spring.data.arangodb.user=root
spring.data.arangodb.password=root



#    docker run -d --name arangodb -p 8529:8529 -e ARANGO_ROOT_PASSWORD=root arangodb
#    http://localhost:8529